### ISSUE TITLE
Publish Error

### ISSUE THREAD

**Issue by gpad** [coders51/rabbitmq-stream-js-client#14]
https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbitmq_stream/docs/PROTOCOL.adoc#publisherror

What does it mean?

**Comment by ablease** [comment]
Hey @gpad  I think this issue can be closed, since publish Errors were included as part of this PR https://github.com/coders51/rabbitmq-stream-js-client/pull/73

**Comment by gpad** [comment]
I agree thanks
