### ISSUE TITLE
Error handling best practices

### ISSUE THREAD

**Issue by ttshivers** [coders51/rabbitmq-stream-js-client#164]
I am interested in learning about the best practices for handling connection, publisher, consumer, and timeout errors. Is that mostly out of scope for this library or would failover or retries be considered?

**Comment by tarzacodes** [comment]
The client does not deal with reconnection or failovers directly. We might consider doing so in the future. 
Please have a look at the `connection_closed` listener. 
You can define it whenever you instantiate a new connection (ex: a new client, declare a publisher, or a consumer). 
Here's an example:

**Comment by tarzacodes** [comment]
We added the above example to our examples list!
I'm closing this issue for now so to keep our working board as clean as possible, I might add a comment here when and if we implement auto-reconnecting (and retrying) logic to the client. Thanks for the feedback!
