### ISSUE TITLE
[enhancement] Add the ability to specify a connection name

### ISSUE THREAD

**Issue by SashaYurchenko** [coders51/rabbitmq-stream-js-client#173]
Right now the default name is used which is "Unknown"
<img width="919" alt="Screenshot 2024-01-27 at 17 48 30" src="https://github.com/coders51/rabbitmq-stream-js-client/assets/13157397/3f5aa320-de1e-4669-a165-e5080e091759">

It would be nice to set a friendly name for any new connection by passing it in the client properties.

```ts
export interface ConnectionParams {
    hostname: string;
    port: number;
    ...
    connectionName?: string;
}
```

**Comment by tarzacodes** [comment]
Thanks! This is indeed something we can do, we'll probably bundle this in the next release!
