### ISSUE TITLE
[bug] Stream arguments are ignored when creating a new stream

### ISSUE THREAD

**Issue by SashaYurchenko** [coders51/rabbitmq-stream-js-client#174]
It is not possible to define stream retention policies during the stream creation, like `x-max-age`, `x-max-length-bytes` or `x-stream-max-segment-size-bytes`. All passed arguments are ignored.

```ts
  const client = await connect({
    hostname: 'localhost',
    port: 5552,
    username: user,
    password: password,
    vhost: '/',
  });

  await client.createStream({
    stream: streamName,
    arguments: {
      'x-max-age': '1d',
      'x-max-length-bytes': 20_000_000_000, // maximum stream size: 20 GB
      'x-stream-max-segment-size-bytes': 100_000_000, // size of segment files: 100 MB
    },
  });
```
<img width="738" alt="Screenshot 2024-01-27 at 18 17 48" src="https://github.com/coders51/rabbitmq-stream-js-client/assets/13157397/a2ba5afc-91e7-4a0a-a4d9-dd792c657206">

**Comment by tarzacodes** [comment]
On it - we'll also add a test on the pipeline to check for this. Expect this to be fixed next release
