### ISSUE TITLE
Allow Customized Consumer Names and Offset for Super Stream Consumers

### ISSUE THREAD

**Issue by haile-vnm** [coders51/rabbitmq-stream-js-client#190]
## Current Behavior
- Currently, when consuming a super stream, the following limitations exist:
  - The Single Active Consumer feature cannot be enabled due to the random generation of consumer names.
  - The consuming point in the super stream is fixed to start from the beginning (`Offset.first()`).

## Expected Behavior
- The expected behavior includes the following improvements:
  - Allow the Single Active Consumer feature by providing a customized consumer reference (`consumerRef`) when declaring the super stream consumer. This would enable users to specify their own consumer names instead of relying on random generation.
  - Allow users to decide the consuming point by providing the option to set the offset when declaring the Single Active Consumer. This would give users the ability to choose a specific point in the super stream from which consumption should begin.

**Comment by icappello** [comment]
Hello, thanks for the opened issue and the PR, much appreciated!

We will give you a feedback shortly.

**Comment by icappello** [comment]
Hello @haile-vnm your contribution has been merged into the codebase, so I'll now close this issue. Thanks again for opening the issue and providing an implementation!
