### ISSUE TITLE
Fail to PubSub after successful connection

### ISSUE THREAD

**Issue by lvskk** [coders51/rabbitmq-stream-js-client#192]
I've started playing with RabbitMQ Streams today in Node and found a weird issue. Even after a successful connection, I wasn't able to publish, subscribe or create streams.

As I'm only playing around, I only have one node running.

## Expected Behavior
After a successful connection, further issued commands should work.

## Current Behavior
![image](https://github.com/coders51/rabbitmq-stream-js-client/assets/35465648/f6e23312-e177-42ed-9785-13e5b3e9e1f1)

## Possible Solution
On the client.js file, under the getConnection function, the chosenNode variable is presenting the computer name, instead of the hostname provided when instantiating the client.
![image](https://github.com/coders51/rabbitmq-stream-js-client/assets/35465648/b9c9a7b1-3495-4072-9779-f1094a816d2e)

As a workaround, I've added a singleNode parameter to the connect constructor.
![image](https://github.com/coders51/rabbitmq-stream-js-client/assets/35465648/488db65b-b62c-4fac-82c9-ac9b83c63da3)

And added this to the client.js file
![image](https://github.com/coders51/rabbitmq-stream-js-client/assets/35465648/feed7f89-20c6-47fd-b0cb-5b6f95305c0c)

Now it uses the hostname provided on the constructor to issue new commands, worked like a charm.

I'm not making a PR as I'm not experienced on RabbitMQ and don't know if it's intended to work this way, just my 0.02$.

**Comment by icappello** [comment]
Hello, could you check the `stream.advertised_host` parameter in your rabbitmq server configuration? By default it returns the hostname of the node server.

See here for reference: https://www.rabbitmq.com/docs/stream#advertised-host-port

**Comment by lvskk** [comment]
It's undefined on my setup, idk but probably defaults to the machine name

Thx for the input

![image](https://github.com/coders51/rabbitmq-stream-js-client/assets/35465648/3ad59da1-14b7-4b1c-8cf6-393de4d8df30)

**Comment by icappello** [comment]
No problem! I'll close this issue for the time being.
