### ISSUE TITLE
An error occurred: Error: getaddrinfo ENOTFOUND 5b00f126b101

### ISSUE THREAD

**Issue by MKroezen** [coders51/rabbitmq-stream-js-client#210]
I get an error when trying to declare the publisher.

Code Example:

```
const rabbit = require('rabbitmq-stream-js-client');

async function main() {
  try {
    const client = await rabbit.connect({
      hostname: 'localhost',
      port: 5552,
      username: 'guest',
      password: 'guest',
      vhost: '/',
    });

    await client.createStream({ stream: 'stream-name' });

    const publisher = await client.declarePublisher({
      stream: 'stream-name',
    });
  } catch (error) {
    console.error('An error occurred:', error);
  }
}

main();
```

Error: `
An error occurred: Error: getaddrinfo ENOTFOUND 5b00f126b101
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '5b00f126b101'
}
`

Node version v20.16.0
Platform windows

Running RabbitMQ in Docker and the stream is created by code.

**Comment by hamidovz** [comment]
@MKroezen  hi ! how did you solve the problem ?
