### ISSUE TITLE
Fix: Credit test fails

### ISSUE THREAD

**Issue by l4mby** [coders51/rabbitmq-stream-js-client#88]
This test fail because (I think) there is a bug in the consumer see the pr #86. But it's fine to skip it for now. 
_Originally posted by @gpad in https://github.com/coders51/rabbitmq-stream-js-client/pull/75#discussion_r1178688759_

**Comment by tarzacodes** [comment]
We decided to remove the test as we found it unfeasible to make it reliable in the pipeline
